---

- name: Connect to VMware HCI
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars:

    validate_certs: false

  tasks:
    - name: Get vCenter info
      vmware_about_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
      register: vc_info

    - debug:
        var: vc_info

